### ISSUE TITLE
¿Detectar producto existente?

### ISSUE THREAD

**Issue by fzzio** [woowup/woowup-php-client#8]
Hola!

En la la clase `Users.php` existe un método **exist** para verificar si un usuario existe o no, ¿Cómo se haría para verificar lo mismo en `Products.php `? ya que el API solo me devuelve 404 si hago un UPDATE y el ID no existe.

Es netamente para usar algo como en Users así:
```
if (!$woowup->products->exist( $sku )) {
	$response = $woowup->products->create($productoWoowUp);

	echo "existe";
} else {
	echo "No existe";
}
```

Saludos.

**Comment by diegorivas89** [comment]
Hola @fzzio!

En productos no tenemos el **exist** como en clientes por que en la mayoría de los casos que se necesita es por que se está actualizando/creando el catalogo de productos, por lo que recomendamos para hacer menos request hagas el update del producto, en los casos que obtengas un 404, hacer un create del producto (el payload en ambos es igual).

Si la idea es periódicamente actualizar el catalogo de productos, vas a estar haciendo **solo un** request contra la API en la mayoría de los casos. Ahora si necesitas chequear la existencia de un producto sin una acción posterior, podemos actualizar la API y agregarlo.

Podes ver la documentación entera de la API en https://docs.woowup.com/, el cliente de PHP lo seguimos desarrollando por que internamente lo usamos pero es bienvenido cualquier pull-request :)

Saludos!

**Comment by fzzio** [comment]
Hola @diegorivas89 

El cliente PHP está muy bueno, de hecho iba a hacer un pull-request de la clase **Products.php** hace unos días. Pero luego hice `composer update` y me fijé que ya la habían incluido jaja.

Si, me interesaría saber el tema de existencias a través del API al igual que lo tienen en Users. No tengo acciones posteriores, de hecho lo uso justamente para no volver a agregar el mismo producto ya que lo comparo con una base de datos mía.

Saludos!

**Comment by diegorivas89** [comment]
@fzzio 

Vamos a estar trabajando en el cliente para seguir cubriendo endpoints de la API, cualquier consejo es bienvenido :)

Con respecto al **exist** vamos a estar agregándolo en la próxima semana, también para las ventas de forma que sea un standard en nuestra API, cuando lo tengamos productivo te aviso por acá mismo.

Saludos

**Comment by diegorivas89** [comment]
Hola @fzzio,

Ya está en producción el endpoint para chequear si existe un producto o no al igual que clientes.
La documentación la puedes ver aquí:

https://docs.woowup.com/api/products.html#get-productsidexist

Espero que te sirva!

Saludos
